export enum PerformerType {
  ROOT = 'ROOT',
  STATE_HEAD = 'STATE HEAD',
  ADMIN = 'ADMIN',
  EMPLOYEE = 'EMPLOYEE',
  MASTER_DISTRIBUTOR = 'MASTER DISTRIBUTOR',
  DISTRIBUTOR = 'DISTRIBUTOR',
  RETAILER = 'RETAILER',
}

export enum TargetUserType {
  ROOT = 'ROOT',
  STATE_HEAD = 'STATE HEAD',
  ADMIN = 'ADMIN',
  EMPLOYEE = 'EMPLOYEE',
  MASTER_DISTRIBUTOR = 'MASTER DISTRIBUTOR',
  DISTRIBUTOR = 'DISTRIBUTOR',
  RETAILER = 'RETAILER',
}

export enum AuditStatus {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  PENDING = 'PENDING',
}
