export enum WebhookStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  RETRY = 'RETRY',
}

export enum WebhookEventType {
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  REFUND_INITIATED = 'REFUND_INITIATED',
  REFUND_COMPLETED = 'REFUND_COMPLETED',
  REFUND_FAILED = 'REFUND_FAILED',
  SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_RENEWED = 'SUBSCRIPTION_RENEWED',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
  ENTITY_VERIFIED = 'ENTITY_VERIFIED',
  ENTITY_REJECTED = 'ENTITY_REJECTED',
  KYC_APPROVED = 'KYC_APPROVED',
  KYC_REJECTED = 'KYC_REJECTED',
  CUSTOM = 'CUSTOM',
}

export enum WebhookProvider {
  BULKPE = 'BULKPE',
  PAYTM = 'PAYTM',
  RAZORPAY = 'RAZORPAY',
  CCAVENUE = 'CCAVENUE',
  BILLDESK = 'BILLDESK',
  AIRTEL = 'AIRTEL',
  JIO = 'JIO',
  OTHER = 'OTHER',
}
