@dev = http://localhost:9000
@baseUrl = {{dev}}/api/v1

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNDFmNWM4ZS02N2E5LTRkM2MtYjIyZi02YjZiMWRlODBlMjYiLCJwcmluY2lwYWxUeXBlIjoiUk9PVCIsInJvbGVJZCI6ImYwYTI2Zjg5LWE3Y2MtNDQ2NC1hZjU5LTQ1ZWRmYjA2ZDI2ZiIsImlzUm9vdCI6dHJ1ZSwiaWF0IjoxNzY1MDAxNDA2LCJleHAiOjE3NjUwMDUwMDZ9.52T0lc9e572k7S10FUD1cUbMhzmZQxhUJap3FxflyJ0
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNDFmNWM4ZS02N2E5LTRkM2MtYjIyZi02YjZiMWRlODBlMjYiLCJwcmluY2lwYWxUeXBlIjoiUk9PVCIsInJvbGVJZCI6ImYwYTI2Zjg5LWE3Y2MtNDQ2NC1hZjU5LTQ1ZWRmYjA2ZDI2ZiIsImlzUm9vdCI6dHJ1ZSwiaWF0IjoxNzY1MDAxNDA2LCJleHAiOjE3Njc1OTM0MDZ9.HUt3hC5we_o78VgKIFEbwcGsVRuya10e9apTyhAa13I


### HEALTH CHECK
GET {{baseUrl}}/health


### ROOT LOGIN
POST {{baseUrl}}/root/auth/login
Content-Type: application/json

{
  "email": "root@system.com",
  "password": "Root@123"
}


### ROOT LOGOUT
POST {{baseUrl}}/root/auth/logout
Authorization: Bearer {{accessToken}}


### REFRESH TOKEN
POST {{baseUrl}}/root/auth/refresh-token
Cookie: refresh_token={{refreshToken}}


### ME
GET {{baseUrl}}/root/auth/me
Authorization: Bearer {{accessToken}}


### DASHBOARD
GET {{baseUrl}}/root/auth/dashboard
Authorization: Bearer {{accessToken}}


### UPDATE CREDENTIALS
PATCH {{baseUrl}}/root/auth/credentials
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "currentPassword": "oldpass",
  "newPassword": "newpass123"
}


### UPDATE PROFILE
PATCH {{baseUrl}}/root/auth/profile
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "firstName": "Root",
  "lastName": "Admin",
  "username": "rootmaster",
  "email": "root@example.com",
  "phoneNumber": "9876543210"
}


### UPDATE PROFILE IMAGE
PATCH {{baseUrl}}/root/auth/profile-image
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=----Form

------Form
Content-Disposition: form-data; name="profileImage"; filename="profile.jpg"
Content-Type: image/jpeg

< ./path/to/profile.jpg
------Form--


### REQUEST PASSWORD RESET
POST {{baseUrl}}/root/auth/request-password-reset
Content-Type: application/json

{
  "email": "root@example.com"
}


### CONFIRM PASSWORD RESET
POST {{baseUrl}}/root/auth/confirm-password-reset
Content-Type: application/json

{
  "token": "your-token-hhere"
}