export enum EntityStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum ProviderType {
  BULKPE = 'BULKPE',
  PAYTM = 'PAYTM',
  RAZORPAY = 'RAZORPAY',
  CCAVENUE = 'CCAVENUE',
  BILLDESK = 'BILLDESK',
  AIRTEL = 'AIRTEL',
  JIO = 'JIO',
  OTHER = 'OTHER',
}
